Process management
Ethan3600/EthanYehuda_CronjobManager pull request #100
Opened 2019-02-11 07:37 UTC by schmengler

Resolves #95 

- Running jobs kann be requested to be killed from the grid
- Kill requests are processed on next cron execution, job status is set to "killed" on success
- Messages from killed and cleared jobs contain timestamp
- Refactoring of pid save method and CleanRunningJobsObserver

2019-02-16 21:08 UTC, Ethan3600 requested changes
Few comments. I think this feature going to help a lot!

Biggest thing here is the constant visibility. PHP 7.0 doesn't support it, and if we want to keep the code as is then we need to consider dropping support for PHP 7.0. I'm not opposed to it, but a lot of users of Magento 2.2.x may still be using PHP 7.0.

Thanks @schmengler and @tbaden for this tremendous contribution!

2019-02-16 21:08 UTC, Ethan3600 commented on view/adminhtml/ui_component/cronjobmanager_manage_grid.xml
> +		<column name="pid">
More of a nitpick:

Not sure if this is happening for you, but for some reason the PID column shows up at the end of the grid after the "action" column. I just think it's awkward. Maybe we should move this up? Your call.

2019-02-16 21:08 UTC, Ethan3600 commented on Model/CleanRunningJobs.php
> +            $messages[] = 'Process went away';
Maybe we should wrap "Process went away" in a translator function `__()`

2019-02-16 21:08 UTC, Ethan3600 commented on Model/CleanRunningJobs.php
> +            $messages[] = 'Process went away at ' . $this->dateTime->gmtDate(null, $this->clock->now());
I know it wasn't there before, but maybe this should also be wrapped in the translator function?

2019-02-16 21:08 UTC, Ethan3600 commented on Test/Integration/CleanDeadJobsTest.php
> +    private const DEAD_PID = 99999999;
This will cause an error in PHP 7.0. Magento 2.2.x still supports 7.0, so I'm not sure we should drop support yet.

However, I'm open to an argument for dropping support for 7.0.

2019-02-16 21:08 UTC, Ethan3600 commented on Model/ProcessManagement.php
> +    private const SIGKILL = 9;
This will cause an error in PHP 7.0 (see previous comment)

2019-02-16 21:08 UTC, Ethan3600 commented on Test/Integration/CleanRunningJobsTest.php
> +    private const NOW = '2019-02-09 18:33:00';
This will cause an error in PHP 7.0 (see previous comment)

2019-02-16 21:08 UTC, Ethan3600 commented on Test/Integration/CleanRunningJobsTest.php
>      private const DEAD_PID = 99999999;
This will cause an error in PHP 7.0 (see previous comment)

2019-02-16 21:08 UTC, Ethan3600 commented on Test/Integration/ProcessKillRequestsTest.php
> +    private const NOW = '2019-02-09 18:33:00';
This will cause an error in PHP 7.0 (see previous comment)

2019-02-16 21:08 UTC, Ethan3600 commented on Api/Data/ScheduleInterface.php
> +    public const STATUS_KILLED  = 'killed';
This will cause an error in PHP 7.0 (see previous comment)

2019-02-16 21:08 UTC, Ethan3600 commented on Api/Data/ScheduleInterface.php
>      public const STATUS_ERROR   = Schedule::STATUS_ERROR;
This will cause an error in PHP 7.0 (see previous comment)

2019-02-18 11:02 UTC, schmengler commented on Test/Integration/CleanDeadJobsTest.php
> +    private const DEAD_PID = 99999999;
Here's an argument for dropping 7.0 support: https://secure.php.net/supported-versions.php :grin:

2019-02-18 11:04 UTC, schmengler commented on Test/Integration/CleanDeadJobsTest.php
> +    private const DEAD_PID = 99999999;
But if it's only the private constants so far and you decide to wait with dropping 7.0 compatibility, e.g. until next major release, I'm fine with changing it.

2019-02-22 09:47 UTC, schmengler commented on view/adminhtml/ui_component/cronjobmanager_manage_grid.xml
> +		<column name="pid">
Seems like after changes in column orders, cleaning up the `ui_bookmark` table is necessary...

2019-02-22 10:01 UTC, schmengler commented
@Ethan3600 thanks for your feedback, please take a look again!

2019-02-22 10:06 UTC, schmengler commented on Test/Integration/CleanDeadJobsTest.php
> +    private const DEAD_PID = 99999999;
Moved the decision to a separate issue: #110

2019-02-27 01:02 UTC, merged