[ADD] consistent navigation in all admin menus
Ethan3600/EthanYehuda_CronjobManager pull request #104
Opened 2019-02-11 08:24 UTC by tbaden

2019-02-16 18:42 UTC, Ethan3600 requested changes
Few comments. This looks great, but there were a few issues.

This will surely improve navigation. Thanks for the contribution!

2019-02-16 18:42 UTC, Ethan3600 commented on view/adminhtml/ui_component/cronjobmanager_timeline.xml
> +				<item name="url" xsi:type="string">*/*/create</item>
This should be `*/manage/create`

2019-02-16 18:42 UTC, Ethan3600 commented on view/adminhtml/ui_component/cronjobmanager_timeline.xml
> +				<item name="url" xsi:type="string">*/config_job/run</item>
If we're going to add this functionality here, then we need to refactor [the Run controller](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/Controller/Adminhtml/Config/Job/Run.php).

Essentially, instead of `$this->_redirect('*/config/');` we should do this:

```php
$resultRedirect->setUrl($this->_redirect->getRefererUrl());
return $resultRedirect;
```

This is so we redirect the user back to where they came from, and not to the Job Configuration page (that'd be very confusing I think).

2019-02-16 18:42 UTC, Ethan3600 commented on view/adminhtml/ui_component/cronjobmanager_timeline.xml
> +				<item name="url" xsi:type="string">*/config_job/run</item>
I'll leave this here: https://magento.stackexchange.com/questions/94977/how-to-redirect-to-previous-page-magento-2

I'll note that there is a "resultFactory" in the Action class the controller inherits from, so no need to inject that in.

2019-02-16 18:42 UTC, Ethan3600 commented on view/adminhtml/ui_component/cronjobmanager_manage_grid.xml
> +				<item name="url" xsi:type="string">*/config_job/run</item>
Let's make sure this controller redirects back to where they were referred from. See my other comment about the Run controller.

2019-02-16 18:42 UTC, Ethan3600 commented on view/adminhtml/ui_component/cronjobmanager_config_grid.xml
> +				<item name="url" xsi:type="string">*/*/create</item>
`*/manage/create`

Otherwise, we'll have an infinite redirect

2019-02-16 18:42 UTC, Ethan3600 commented on view/adminhtml/ui_component/cronjobmanager_manage_grid.xml
>  				<item name="url" xsi:type="string">*/*/create</item>
Although this would work perfectly, I think we should be explicit and change this to`*/manage/create` just to keep things consistent. I'll leave it to you.

2019-03-09 20:09 UTC, Ethan3600 commented
@tbaden Do you want me to take ownership of this PR? I want this to be a part of the next release as I think it adds a lot of value. Just don't want to step on your toes.

2019-03-16 19:51 UTC, Ethan3600 commented
Since there hasn't been a response in a while, I'm going to pull over your changes into a separate branch and continue from there.

2019-03-16 19:51 UTC, closed without merging

2019-04-13 15:08 UTC, tbaden commented
@Ethan3600 
thanks for the work. I'm rather inactive on github between hackathons. keep up the good work.

2019-04-13 16:09 UTC, Ethan3600 commented
No worries at all! Thanks for contributing!