Keep track of PID and clean up "lost" processes
Ethan3600/EthanYehuda_CronjobManager pull request #57
Opened 2018-05-08 12:58 UTC by AndreKlang

## Code
Solves one requirement of https://github.com/Ethan3600/magento2-CronjobManager/issues/19 (Track PID of each cron job).

Also adds another feature, cleaning of jobs in cron_schedude table that has status "running", but the process is missing from the current system. There is a system config to disable this behavior in admin.

Seeing that this is a new feature added, I bumped the version to 1.6.0. I am fine with changing this if you wish.

## Background
In our environment the cron process runs on a node that can be shut down and moved quite randomly, causing jobs to die mid-way through. This leaves a process in "running" status forever. It also stops any following jobs from running, except the scheduler. So that keeps adding all future jobs to the list, a few thousand per day. And that in turn puts enormous load on our DB server.

I hope you'll accept this pull request, even though we did not discuss it first, I simply needed our issue solved right away, and seeing that this was on the roadmap anyway it seemed wrong to put it in it's own module.

//Andre Klang
PS: Thanks for your great module!

2018-05-08 23:43 UTC, Ethan3600 commented
@AndreKlang Great work! I've been really meaning to get this functionality in the CJM, so thank you for your amazing contribution!

One thing before I can start reviewing. Can we can rebase on top of 1.x-develop to get rid of those merges / pull requests? I really should document that better somewhere.. I may even remove those two branches and start making releases off the develop branches.

I just don't want to start reviewing and then see the reviews disappear. Sorry for the inconvenience.

2018-05-09 06:36 UTC, AndreKlang commented
@Ethan3600 Ah, glad it was well received :)

I *think* that I've done the rebase as you asked, GitHub and rebase between branches is not my strong suit..

A suggestion about your branches, if you want to reorganize anyway, look into GitFlow (http://nvie.com/posts/a-successful-git-branching-model/), it's basically the same structure that you have now, just stricter. We use that model internally and it has really helped alot..

2018-05-09 13:38 UTC, Ethan3600 commented
@AndreKlang That's perfect, I'll start reviewing tonight. Thanks for the suggestion! I'll do some homework on GitFlow.

2018-05-10 02:06 UTC, Ethan3600 requested changes
This was very well done! I just have a few questions, and change requests. Mostly minor things.

Sorry in advance for the nitpicks! :innocent:

2018-05-10 02:06 UTC, Ethan3600 commented on Plugin/Cron/Model/SchedulePlugin.php
>              $subject->setData("pid", \getmypid());
Does `getmypid()` not work without the backslash "\\" ?

2018-05-10 02:06 UTC, Ethan3600 commented on Observer/CleanRunningJobsObserver.php
> +        // https://stackoverflow.com/questions/9874331/how-to-check-whether-specified-pid-is-currently-running-without-invoking-ps-from
Magento doesn't support other operating systems besides, so neither should we
https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html#operating-systems-linux-x86-64

Let's remove this.

2018-05-10 02:06 UTC, Ethan3600 commented on Observer/CleanRunningJobsObserver.php
> +            ;
nit: let's end put this semicolon at the end of the previous statement

2018-05-10 02:06 UTC, Ethan3600 commented on Observer/CleanRunningJobsObserver.php
> +        \Magento\Cron\Model\ResourceModel\Schedule $resourceModel
nit: Let's move this up with the namespaces and add a `use`

`use Magento\Cron\Model\ResourceModel\Schedule`

2018-05-10 02:06 UTC, Ethan3600 commented on Observer/CleanRunningJobsObserver.php
> +        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
nit: same thing here. Let's use a `use` for these namespaces

2018-05-10 02:06 UTC, Ethan3600 commented on etc/adminhtml/system.xml
> +                <label>Cron Manager</label>
Can we change this to Cron Job Manager? For the sake of consistency.

2018-05-10 02:06 UTC, Ethan3600 commented on Plugin/Cron/Model/SchedulePlugin.php
> +        \Magento\Cron\Model\ResourceModel\Schedule $resourceModel
nit: Let's use a `use` and move this underneath `namespace`

2018-05-10 02:06 UTC, Ethan3600 commented on etc/di.xml
> +        <plugin name="ethanyehuda_cronjobmanager_set_pid" type="\EthanYehuda\CronjobManager\Plugin\Cron\Model\SchedulePlugin" />
Does this work with the leading backslash? I think this would throw errors when the object manager tries to resolve this, no?

2018-05-10 02:06 UTC, Ethan3600 commented on Plugin/Cron/Observer/ProcessCronQueueObserverPlugin.php
> +        $this->eventManager->dispatch("process_cron_queue_before", ["queue" => $subject]);
No need to change anything if it's not necessary, but why not put everything in the `CleanRunningJobsObserver` class in this plugin?

2018-05-10 02:06 UTC, Ethan3600 commented on etc/crontab/events.xml
> +        <observer name="ethanyehuda_cronjobmanager_clean_running_jobs" instance="\EthanYehuda\CronjobManager\Observer\CleanRunningJobsObserver" />
I think the leading backslash will cause problems, no?

2018-05-11 06:06 UTC, AndreKlang commented on Plugin/Cron/Model/SchedulePlugin.php
>              $subject->setData("pid", \getmypid());
It does work without, but its a global function so it is defined in the root namespace, hence the \.
PhpStorm puts them there by default, so I usually leave it..
I've removed it (and one other) for the sake of consistency

2018-05-11 06:06 UTC, AndreKlang commented on Observer/CleanRunningJobsObserver.php
> +        // https://stackoverflow.com/questions/9874331/how-to-check-whether-specified-pid-is-currently-running-without-invoking-ps-from
Good point :)
Agreed

2018-05-11 06:21 UTC, AndreKlang commented on Observer/CleanRunningJobsObserver.php
> +            ;
I've moved it, I know this is uncommon, but having it on it's own row makes it easier to add/remove/comment-out things in the stack without moving the colon all the time..

But this is actually interesting, the position of it is not (to my knowlege) controlled by any of PSR-2, PSR-4 or Magento's standard (https://github.com/magento-ecg/coding-standard)

2018-05-11 06:24 UTC, AndreKlang commented on etc/di.xml
> +        <plugin name="ethanyehuda_cronjobmanager_set_pid" type="\EthanYehuda\CronjobManager\Plugin\Cron\Model\SchedulePlugin" />
Seeing that EthanYehuda is a root namespace, the leading \ is correct, however, Magento handle both, so it doesn't matter. I've removed all my leading backslashes in the xml-files for consistency with existing code.

2018-05-11 06:44 UTC, AndreKlang commented on Plugin/Cron/Observer/ProcessCronQueueObserverPlugin.php
> +        $this->eventManager->dispatch("process_cron_queue_before", ["queue" => $subject]);
There is actually a few (give it small) reasons I did this:

* Personal preference, I try to keep plugins to bare minimum because of:
* By reading the folder-structure and name `Plugin/Cron/Observer/ProcessCronQueueObserverPlugin.php` gives no hint what so ever what is going on in that file, it does give a hint about what is beeing plugged in to.
  And the name `Observer/CleanRunningJobsObserver.php` gives a good hint about what is happening there..
* Plugins is intended to modify params going in, or returns going out, adding whole new features is a bit of a stretch (I think)
* Dispatching an event can have benefits down the line if anything more needs it
* In this specific case, I acctually built the observer to listen to the `default`-event (same event that `ProcessCronQueueObserver` observes), but that caused my observer to run last. So I simply added an earlier event and changed the xml.

By the logic above, my other plugin, `SchedulePlugin`, goes against this, but in that case the change is directly related to the `$subject`, and the method that is in the plugin.
Adding an event there would make things harder to grasp.

2018-05-11 06:50 UTC, AndreKlang commented
@Ethan3600 Thank you, nice to hear :smile:

I'm a nitpicker myself so no worries, I've pushed a new commit with fixes, and replied to your questions. Looking forward for a new (final?) review!

2018-05-13 02:09 UTC, Ethan3600 commented on Plugin/Cron/Observer/ProcessCronQueueObserverPlugin.php
> +        $this->eventManager->dispatch("process_cron_queue_before", ["queue" => $subject]);
Thanks for sharing! This makes total sense to me now.

2018-05-13 02:10 UTC, merged

2018-05-13 17:16 UTC, Ethan3600 commented
@AndreKlang Thanks again for your contribution!