Fix command error 'area is already set'
Ethan3600/EthanYehuda_CronjobManager pull request #77
Opened 2018-10-15 15:45 UTC by haelbichalex

2018-10-23 13:37 UTC, Ethan3600 commented
@haelbichalex Sorry for the inactivity, I'll try to review this PR this week!

2018-10-24 19:29 UTC, Ethan3600 requested changes
One tiny change and we can get this merged in!

2018-10-24 19:29 UTC, Ethan3600 commented on Console/Command/Runjob.php
> +                $this->state->setAreaCode('adminhtml');
Let's use `Area::AREA_ADMINHTML` here too

2018-10-25 14:35 UTC, haelbichalex commented
Done :white_check_mark:

2018-10-25 17:40 UTC, Ethan3600 commented
Just want to confirm one thing here: https://github.com/Ethan3600/magento2-CronjobManager/pull/77/files#diff-2e06a05bbdb681d5be7c59da0d9a3ee4R67

`getAreaCode()` [throws an exception](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/App/State.php#L151), if the area code is not set.

Is the expectation here to catch that exception? https://github.com/Ethan3600/magento2-CronjobManager/blob/9c490d5db3b162d7e4ec7a01b784b168ec773130/Console/Command/Runjob.php#L79

In the above scenario, the command will always fail. Not good.

Maybe we should remove the setAreaCode() outside the try/catch that it's in and move it it's own try/catch?

like this:

```php
try {
    $this->state->setAreaCode(Area::AREA_ADMINHTML);
} catch (LocalizedException $e) {
    // Area code is already set
}

try {
    // lets create a new cron job and dispatch it
    $jobCode = $input->getArgument(self::INPUT_KEY_JOB_CODE);
    $now = strftime('%Y-%m-%dT%H:%M:%S', $dateTime->gmtTimestamp());
    ..... rest of the code here
```

This way, we're always attempting to set the areaCode, and if it's already set, then the command will still run.

2018-11-06 16:18 UTC, Ethan3600 commented
@haelbichalex I think it's worth making that change as I mentioned in the previous comment. I believe it's more robust. Let me know what you think!

2018-11-29 09:33 UTC, haelbichalex commented
@Ethan3600 Sorry for the delay. As suggested I moved the `setAreaCode()` to its own try-catch block as its independent of the other exception. Did work like expected on my M2 instance 👍

2018-12-01 23:31 UTC, merged