Rest API Support
Ethan3600/EthanYehuda_CronjobManager pull request #87
Opened 2018-12-23 15:54 UTC by pmclain

This PR creates a number of Rest API endpoints for viewing and managing crons. Creates repository and management interfaces that separate out most of the logic in current `Manager` class. `Manager` is reduced to a legacy adapter passing requests to the appropriate interface and should probably be deprecated and removed in a future release. 

Below are the relevant swagger docs output from `https://{{storeUrl}}/swagger` using a valid admin access token:

```yaml
swagger: '2.0'
info:
  version: 1.x
basePath: /rest/all
schemes:
  - https
tags:
  - name: ethanYehudaCronjobManagerScheduleRepositoryV1
    description: ''
  - name: ethanYehudaCronjobManagerScheduleRepositoryAdapterV1
    description: Adapter used by REST API to work around the lack of data getters and setters in \Magento\Cron\Model\Schedule making the core cron model incompatible with param and result resolvers.
  - name: ethanYehudaCronjobManagerScheduleManagementV1
    description: ''
  - name: ethanYehudaCronjobManagerScheduleManagementAdapterV1
    description: Adapter used by REST API to work around the lack of data getters and setters in \Magento\Cron\Model\Schedule making the core cron model incompatible with param and result resolvers.
paths:
  '/V1/cronmanager/schedules/{scheduleId}':
    delete:
      tags:
        - ethanYehudaCronjobManagerScheduleRepositoryV1
      description: ''
      operationId: ethanYehudaCronjobManagerScheduleRepositoryV1DeleteByIdDelete
      parameters:
        - name: scheduleId
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: 200 Success.
          schema:
            type: boolean
            description: True on success
        '401':
          description: 401 Unauthorized
          schema:
            $ref: '#/definitions/error-response'
        '500':
          description: Internal Server error
          schema:
            $ref: '#/definitions/error-response'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error-response'
    get:
      tags:
        - ethanYehudaCronjobManagerScheduleRepositoryAdapterV1
      description: ''
      operationId: ethanYehudaCronjobManagerScheduleRepositoryAdapterV1GetGet
      parameters:
        - name: scheduleId
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: 200 Success.
          schema:
            $ref: '#/definitions/ethan-yehuda-cronjob-manager-data-schedule-interface'
        '401':
          description: 401 Unauthorized
          schema:
            $ref: '#/definitions/error-response'
        '500':
          description: Internal Server error
          schema:
            $ref: '#/definitions/error-response'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error-response'
    put:
      tags:
        - ethanYehudaCronjobManagerScheduleRepositoryAdapterV1
      description: ''
      operationId: ethanYehudaCronjobManagerScheduleRepositoryAdapterV1SavePut
      parameters:
        - name: scheduleId
          in: path
          type: integer
          required: true
        - name: ethanYehudaCronjobManagerScheduleRepositoryAdapterV1SavePutBody
          in: body
          schema:
            required:
              - schedule
            properties:
              schedule:
                $ref: '#/definitions/ethan-yehuda-cronjob-manager-data-schedule-interface'
            type: object
      responses:
        '200':
          description: 200 Success.
          schema:
            $ref: '#/definitions/ethan-yehuda-cronjob-manager-data-schedule-interface'
        '401':
          description: 401 Unauthorized
          schema:
            $ref: '#/definitions/error-response'
        '500':
          description: Internal Server error
          schema:
            $ref: '#/definitions/error-response'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error-response'
  /V1/cronmanager/schedules:
    get:
      tags:
        - ethanYehudaCronjobManagerScheduleRepositoryAdapterV1
      description: ''
      operationId: ethanYehudaCronjobManagerScheduleRepositoryAdapterV1GetListGet
      parameters:
        - name: 'searchCriteria[filterGroups][0][filters][0][field]'
          in: query
          type: string
          description: Field
        - name: 'searchCriteria[filterGroups][0][filters][0][value]'
          in: query
          type: string
          description: Value
        - name: 'searchCriteria[filterGroups][0][filters][0][conditionType]'
          in: query
          type: string
          description: Condition type
        - name: 'searchCriteria[sortOrders][0][field]'
          in: query
          type: string
          description: Sorting field.
        - name: 'searchCriteria[sortOrders][0][direction]'
          in: query
          type: string
          description: Sorting direction.
        - name: 'searchCriteria[pageSize]'
          in: query
          type: integer
          description: Page size.
        - name: 'searchCriteria[currentPage]'
          in: query
          type: integer
          description: Current page.
      responses:
        '200':
          description: 200 Success.
          schema:
            $ref: '#/definitions/ethan-yehuda-cronjob-manager-data-schedule-search-results-interface'
        '401':
          description: 401 Unauthorized
          schema:
            $ref: '#/definitions/error-response'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error-response'
    post:
      tags:
        - ethanYehudaCronjobManagerScheduleRepositoryAdapterV1
      description: ''
      operationId: ethanYehudaCronjobManagerScheduleRepositoryAdapterV1SavePost
      parameters:
        - name: ethanYehudaCronjobManagerScheduleRepositoryAdapterV1SavePostBody
          in: body
          schema:
            required:
              - schedule
            properties:
              schedule:
                $ref: '#/definitions/ethan-yehuda-cronjob-manager-data-schedule-interface'
              scheduleId:
                type: integer
            type: object
      responses:
        '200':
          description: 200 Success.
          schema:
            $ref: '#/definitions/ethan-yehuda-cronjob-manager-data-schedule-interface'
        '401':
          description: 401 Unauthorized
          schema:
            $ref: '#/definitions/error-response'
        '500':
          description: Internal Server error
          schema:
            $ref: '#/definitions/error-response'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error-response'
  '/V1/cronmanager/schedules/{scheduleId}/execute':
    put:
      tags:
        - ethanYehudaCronjobManagerScheduleManagementV1
      description: ''
      operationId: ethanYehudaCronjobManagerScheduleManagementV1ExecutePut
      parameters:
        - name: scheduleId
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: 200 Success.
          schema:
            type: boolean
        '401':
          description: 401 Unauthorized
          schema:
            $ref: '#/definitions/error-response'
        '500':
          description: Internal Server error
          schema:
            $ref: '#/definitions/error-response'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error-response'
  /V1/cronmanager/schedules/flush:
    delete:
      tags:
        - ethanYehudaCronjobManagerScheduleManagementV1
      description: ''
      operationId: ethanYehudaCronjobManagerScheduleManagementV1FlushDelete
      responses:
        '200':
          description: 200 Success.
          s [...]

2019-01-05 19:47 UTC, Ethan3600 requested changes
@pmclain Sorry it took so long! Just one tiny request and we're ready to go!

2019-01-05 19:47 UTC, Ethan3600 commented on Model/Manager.php
>  class Manager
Let's add an @deprecated here

2019-01-05 20:04 UTC, pmclain commented on Model/Manager.php
>  class Manager
👍 https://github.com/Ethan3600/magento2-CronjobManager/commit/7b3731562df089caf5bc7dd2c7ce54f4a363b300#diff-870fa64c1da6197b24aac47a56903c69R9

2019-01-06 22:05 UTC, Ethan3600 approved these changes

2019-01-06 22:07 UTC, merged