Fixes #91: Replicate native CLI handling to launch cron with correct store id
Ethan3600/EthanYehuda_CronjobManager pull request #93
Opened 2019-02-04 15:19 UTC by kyriog

Explanation of this PR has been done in issue #91.

This is almost a straight implementation of Magento Core Cron command, with two details:
* `$omParams[StoreManager::PARAM_RUN_CODE]` has been set to `Store::ADMIN_CODE` (whereas core is set to `'admin'` literal string)
* `try…catch` around `setAreaCode()` has been removed, as it should not occur anymore with the new `ObjectManager` instance.

2019-02-10 23:41 UTC, Ethan3600 requested changes
A few requests, and ultimately a larger conversation.

I don't want to use the object manager if we can avoid it. I'm struggling to understand the problem because I have no idea how to reproduce your issue. May I ask why your code breaks when it runs "as is" (i.e. with the $storeCode set to the default store). What difference does this make for a custom cron?

I do agree however, that we should be replicating the native cron behavior here. It just sucks that we have to do it this way.

2019-02-10 23:41 UTC, Ethan3600 commented on Model/Cron.php
> +        $manager = $this->managerFactory->create();
The Manager class is officially [deprecated as of v1.7.0](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/Model/Manager.php#L9). Let's use the [ScheduleManagementInterface](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/Api/ScheduleManagementInterface.php) and the [ScheduleRepositoryInterface](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/Api/ScheduleRepositoryInterface.php) instead

2019-02-10 23:41 UTC, Ethan3600 commented on Model/Cron.php
> +            $schedule = $manager->createCronJob($jobCode, $now);
Let's use the repository here instead

2019-02-10 23:41 UTC, Ethan3600 commented on Model/Cron.php
> +            $manager->dispatchCron(null, $jobCode, $schedule);
And over here, we'll use the scheduleManagementInterface

2019-02-10 23:41 UTC, Ethan3600 commented on Model/Cron.php
> +namespace EthanYehuda\CronjobManager\Model;
Maybe this should be `EthanYehuda\CronjobManager\Model\Cron;` and the name of the class should be `Runner`?

I'd prefer not to use this class name because I'd like to avoid confusing "schedule" and "cron." They're the same thing, but it's just getting a little messy :rofl: 

Another reason is because this class's only purpose is to be instantiated by a "special" object manager, and run in the CLI. 

I just want to make sure it's separated out

2019-02-10 23:41 UTC, Ethan3600 commented on Console/Command/Runjob.php
> +        $objectManager = $this->objectManagerFactory->create($omParams);
:cry:

2019-02-10 23:41 UTC, Ethan3600 commented on Console/Command/Runjob.php
> +        ObjectManagerFactory $objectManagerFactory
I'm really not happy that we need to do this. @kyriog is there anyway we can use [di.xml](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/etc/crontab/di.xml) to inject the $scopeCode value upon instantiation?

I feel like the solution here is to inject the parameters we need via di.xml in general.

2019-02-11 10:38 UTC, kyriog commented
Ok, let's explain my use case.

I have a **list** attribute which has a global value, but where each value is different between admin view and websites views.
In my particular case, attribute is a restocking delay value: in admin view, product team defines a number of days from this list, but in frontend, it displays as a "formatted string" (like "3 to 4 weeks").
This is done using the "Manage Options (Values of Your Attribute)" part of attribute management.

In my code, I need to get the admin value of this attribute to send the restock value to our ERP.
Basically, I load a `\Magento\Catalog\Model\ResourceModel\Product\Collection` with the restocking attribute selected (and few filters in order to load only edited producs since last sync), then I get its value using legacy `$product->getAttributeText('restocking_delay')` (It seems there's no equivalent using data API).

What happen is, using core `cron:run`, it loads the admin value of the attribute (let's say, 12), but using your `cronmanager:runjob`, it loads the front value (in this case, "one or two weeks").

I'm unsure if I'll have time to investigate your code review today, but I'll manage this as soon as I can.

2019-02-11 18:30 UTC, kyriog commented on Console/Command/Runjob.php
> +        ObjectManagerFactory $objectManagerFactory
I'm really unsure this could be possible.
To work using di.xml, the `$scopeCode` should be injected when `Magento\Store\Model\StoreResolver` is instantiated.

The problem is that this object is instanced before the module Cron execution (or even instantiation).
In fact, this object is even instanced if you try to run a non-existant cli command or no command at all.

I've put a breakpoint at the first line of its constructor, and this point is always reached when I run:
```
$ xdebug bin/magento cronmanager:runjob test # StoreResolver constructor is ran before Runjob one
$ xdebug bin/magento nonexisting
$ xdebug bin/magento
```

I'm unsure di.xml could be used in that case, as this class seems to be instanced at a very early state of the `bin/magento` command.
I assume this is why M2 native cron reinstantiate the objectManager from the ground.

If you're interested, here's the stacktrace when it reaches `StoreResolver` constructor:
![stacktrace](https://user-images.githubusercontent.com/629831/52584776-49549300-2e33-11e9-80f5-f518aa6720a0.png)

2019-02-11 18:33 UTC, kyriog commented on Model/Cron.php
> +        $manager = $this->managerFactory->create();
My PR hasn't the intent to change [the way you're handling runjob command](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/Console/Command/Runjob.php#L63), but I'll have a look to see how to implement ScheduleManagementInterface.

2019-02-11 18:51 UTC, kyriog commented on Console/Command/Runjob.php
> +        $objectManager = $this->objectManagerFactory->create($omParams);
Yeah, I know this is the ugliest thing in the world.
Should I recommend to put a comment here to put the shame on M2 core code?

Something like:
```php
/**
 * Yeah that's dirty, but it's the way the cron core module works
 * @see Magento\Cron\Console\Command\CronCommand::execute()
 */
```

--- **Off-topic** ---

Magento 2 seems to entirely mess up with some basic concepts.
My goal is to catch every admin product save to send updated data to our ERP.
But when you're in the product edit page (and saving action), the store is correctly set to 0.
This is done directly by the controller ([Edit](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Catalog/Controller/Adminhtml/Product/Edit.php#L47-L50) / [Save](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Catalog/Controller/Adminhtml/Product/Save.php#L108-L110)), which is imo a really poor design, but the fun thing is that the mass attribute update doesn't work the same way.
When you're on the mass attribute update page, and saving process, store isn't set to 0 (which produces the same bug

2019-02-11 19:02 UTC, kyriog commented on Console/Command/Runjob.php
> +        $objectManager = $this->objectManagerFactory->create($omParams);
Yeah, I know this is the ugliest thing in the world.
Should I recommend to put a comment here to put the shame on M2 core code?

Something like:
```php
/**
 * Yeah that's dirty, but it's the way the cron core module works
 * @see Magento\Cron\Console\Command\CronCommand::execute()
 */
```

--- **Off-topic** ---

Magento 2 seems to entirely mess up with some basic concepts.
My goal is to catch every admin product save to send updated data to our ERP.
But when you're in the product edit page (and saving action), the store is correctly set to 0.
This is done directly by the controller ([Edit](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Catalog/Controller/Adminhtml/Product/Edit.php#L47-L50) / [Save](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Catalog/Controller/Adminhtml/Product/Save.php#L108-L110)), which is imo a really poor design, but the fun thing is that the mass attribute update doesn't work the same way.

When you're on the mass attribute update page, and saving process, store isn't set to 0 (which produces the same bug as with the runjob command), and the attribute list (on edit page) is populated by default store values using [getAllOptions()](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Eav/Model/Entity/Attribute/Source/Table.php#L59) to return default options, [directly from the block creation](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Backend/Block/Widget/Form.php#L232)…

PS: You can note that using `setCurrentStore()` as on admin product page may fix our issue, but I'm really unsure we should try to bypass M2 core logic or we may create other side effects.

2019-02-15 12:45 UTC, kyriog commented on Model/Cron.php
> +        $manager = $this->managerFactory->create();
I've made a new commit to use `ScheduleManagementInterfaceFactory` instead of `ManagerFactory`, but doing this analysis made me realize something annoying:

As `ScheduleManagement::createSchedule()` save the Schedule in the database as "Pending", it may create a race condition in a production environment if the native Magento Cron is triggered between the end of `createSchedule()` and the schedule status update in `Processor::runScheduledJob()`, causing a double execution of the schedule.

imo,`createSchedule()` should not save the schedule instance, it should be caller's responsibility, and `execute()` should be able to take a Schedule instance as parameter, to avoid loading the entity from the repository.

This way, the schedule could be created as "Pending", but it will only be saved by the`execute()` method, causing to be saved in database directly with the "Running" status (if we set this status along the `setExecutedAt()`).

I also noticed that `Processor::runJob()` and `runScheduledJob()` have the same code. I think `runJob()` should be removed, or if needed it should directly call `runScheduledJob()`.

2019-02-15 12:46 UTC, kyriog commented on Model/Cron.php
> +            $schedule = $manager->createCronJob($jobCode, $now);
I didn't get why we should use the repository here.

This Schedule is a new schedule, or repository can just load existing entities.

I assumed you meant to use `ScheduleManagementInterfaceFactory`.

2019-02-15 12:47 UTC, kyriog commented on Model/Cron.php
> +namespace EthanYehuda\CronjobManager\Model;
I did not missed this part, I just didn't done this for now, to make the code review easier for you. I'll do it if this updated PR is ok for you.

2019-02-15 12:48 UTC, kyriog commented
I've commented your reviews and I've added a new commit to fit your needs.
If my work is ok for you, just ping me and I'll migrate the `Cron` class to `Runner`.

2019-02-16 18:55 UTC, Ethan3600 commented on Model/Cron.php
> +        $manager = $this->managerFactory->create();
I think you're right. Let's make a separate issue for this (or two?) to keep track. Thanks for pointing this out!

2019-02-16 19:17 UTC, Ethan3600 commented on Console/Command/Runjob.php
> +        $objectManager = $this->objectManagerFactory->create($omParams);
I think we can skip the comment, but I'm not against adding a @TODO here saying "find a way around using Object manager." Not a requirement, but I'll leave it to you.

**--- RE: Off-topic ---**

Magento likes to keep us on our toes :rofl: Magento has so many inconsistencies. It's unfortunate, because we ultimately have to create "work around" code, which eventually we'll have to remove when they "fix" their inconsistency...  <sub>IMO Magento has a big QA issue internally</sub> :speak_no_evil: 

I see, maybe we should experiment with `setCurrentStore()` in the future, but I'd rather emulate core logic too.

2019-02-16 19:22 UTC, Ethan3600 commented
@kyriog Thanks for the comments! This makes much more sense now. Let's move the Cron class to Cron\Runner and I think we're good to go!

2019-02-18 14:25 UTC, kyriog commented on Model/Cron.php
> +        $manager = $this->managerFactory->create();
I've created two issues:
* #108 is about the race condition issue
* #109 is about the `runJob() / runScheduledJob()` quality issue

2019-02-18 14:25 UTC, kyriog commented
I've made requested changes and I've created two issues for comment discussed code.

2019-02-18 21:33 UTC, merged